// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwmONjAKKlZiPFyJ1zLZKPOmjRWrtdJc',
    appId: '1:281213103001:web:142411f60e82ad0eb48108',
    messagingSenderId: '281213103001',
    projectId: 'hackathon2024-7e550',
    authDomain: 'hackathon2024-7e550.firebaseapp.com',
    storageBucket: 'hackathon2024-7e550.firebasestorage.app',
    measurementId: 'G-0RZGZXEPYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT4hUtTQmiILyGpACi8-G6zWYKYhJMP2I',
    appId: '1:281213103001:android:dc79ee82fb27aff3b48108',
    messagingSenderId: '281213103001',
    projectId: 'hackathon2024-7e550',
    storageBucket: 'hackathon2024-7e550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvlki8kvlGorg-mNXwI7e6bLp-ImX806c',
    appId: '1:281213103001:ios:91da2eaa68d92ddcb48108',
    messagingSenderId: '281213103001',
    projectId: 'hackathon2024-7e550',
    storageBucket: 'hackathon2024-7e550.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvlki8kvlGorg-mNXwI7e6bLp-ImX806c',
    appId: '1:281213103001:ios:91da2eaa68d92ddcb48108',
    messagingSenderId: '281213103001',
    projectId: 'hackathon2024-7e550',
    storageBucket: 'hackathon2024-7e550.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgwmONjAKKlZiPFyJ1zLZKPOmjRWrtdJc',
    appId: '1:281213103001:web:ff3cd59ab520bdb1b48108',
    messagingSenderId: '281213103001',
    projectId: 'hackathon2024-7e550',
    authDomain: 'hackathon2024-7e550.firebaseapp.com',
    storageBucket: 'hackathon2024-7e550.firebasestorage.app',
    measurementId: 'G-HT35886YMJ',
  );

}